### ISSUE TITLE
Does packer needed to be run on the pve host itself?

### ISSUE THREAD

**Issue by aracloud** [N7KnightOne/packer-template-debian-11#1]
Hi

I tried with your repo but failed with:
ui error: [1;31mBuild 'proxmox-iso.debian-11' errored after 16 milliseconds 787 microseconds: Post "https://myip:8006/api2/json/access/ticket": x509: certificate signed by unknown authority

Is this because I run packer on a remote linux box?

Thank you

**Comment by jacaudi** [comment]
Hey! Thank you for using my packer template!

 It does not need to be used on the host itself, but any device on the same network. That being said, I think the issue you are running into is unsigned certificate. On l[ine 5 of debian-11-bullseye.source.pkr.hcl](https://github.com/N7KnightOne/packer-template-debian-11/blob/0c15def9ac492c0395a2261ab498b29ebd4f9c19/debian-11-bullseye.source.pkr.hcl#L5), change it from `false` to `true` and see if that fixes your error.
