### ISSUE TITLE
storage_pool_type looks like it is depreciated soon

### ISSUE THREAD

**Issue by aracloud** [N7KnightOne/packer-template-debian-11#2]
» packer build -var-file vars/debian_11.pkrvars.hcl -var-file vars.pkrvars.hcl .
Error: Unsupported attribute

  on debian-11-bullseye.source.pkr.hcl line 34:
  (source code not available)

This object does not have an attribute named "storage_pool_type".

So, I simply removed line 34.

**Comment by jacaudi** [comment]
Updated code to remove line 34 as well
